[package]
name = "surfman-chains"
version = "0.7.0"
authors = ["Alan Jeffrey <ajeffrey@mozilla.com>"]
edition = "2018"
description = "An implementation of double-buffered swap chains for surfman"
license = "MPL-2.0"
repository = "https://github.com/asajeffrey/surfman-chains"

[lib]
path = "lib.rs"

[dependencies]
euclid = "0.22.6"
fnv = "1.0"
log = "0.4"
sparkle = "0.1"
surfman-chains-api = "0.2"
surfman = { git = "https://github.com/sribich/surfman", rev = "93f61c300dcee98f38fa4d1b4a9c972dbf28944e" }
